---
resources:
- name: my-ci
  icon: github
  type: git
  source:
    uri: git@github.com:ketinenis/my-ci.git
    branch: main
- name: image
  type: registry-image
  icon: docker
  source:
    repository: my-ci/image
    username: ((docker_username))
    password: ((docker_password))
    tag: latest


jobs:
  # - name: update-pipeline
  #   plan:
  #     - get: my-ci
  #       trigger: true
  #     - file: my-ci/pipeline.yml
  #       set_pipeline: my-ci
       
  - name: build-and-push
  
    plan:
      - get: my-ci
        trigger: true
      # - put: version
        # params: { pre: build }
      - task: build-task-image
        
        file: build_image.yaml
      - put: image
        params:
          image: image/image.tar