---
resources:
- name: git
  icon: github
  type: git
  source:
    uri: https://github.com/ketineni27/my-ci
    branch: master
- name: image
  type: registry-image
  icon: docker
  source:
    repository: my-ci
    username: ((docker_username))
    password: ((docker_password))
    tag: latest


jobs:
  - name: update-pipeline
    plan:
      - get: my-ci
        trigger: true
      - file: my-ci/pipeline.yml
        set_pipeline: my-ci
       
  - name: build-image
    serial: true
    plan:
      - get: my-ci
        trigger: true
      - put: version
        params: { pre: build }
      - task: build-task-image
        privileged: true
        file: my-ci/build_image.yaml
      - put: image
        params:
          image: image/image
          additional_tags: image/additional-tags